# Label Encoding

In [4]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [11]:
#create a simple dataframe
df=pd.DataFrame({
    'color':['red','blue','green','green','red','blue']
})

In [14]:
df.head()

   color
0    red
1   blue
2  green
3  green
4    red

In [12]:
from sklearn.preprocessing import LabelEncoder
lbl_encoder=LabelEncoder()

In [13]:
lbl_encoder.fit_transform(df[['color']])

C:\Users\harsh\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([2, 0, 1, 1, 2, 0])

In [15]:
lbl_encoder.transform([['red']])

C:\Users\harsh\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([2])

In [16]:
lbl_encoder.transform([['blue']])

C:\Users\harsh\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([0])

In [17]:
lbl_encoder.transform([['green']])

C:\Users\harsh\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([1])

# Ordinal Encoding
#import pandas

In [18]:
from sklearn.preprocessing import OrdinalEncoder

In [20]:
df= pd.DataFrame({
    'size': ['small','medium','large','medium','small','large']
})

In [22]:
df.head(6)

     size
0   small
1  medium
2   large
3  medium
4   small
5   large

In [24]:
#create ab instance of ordinal encoder and then fit_transform
encoder=OrdinalEncoder(categories=[['small', 'medium','large']])

In [25]:
encoder.fit_transform(df[['size']])

array([[0.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.]])

In [29]:
encoder.transform([['medium']])

C:\Users\harsh\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

array([[1.]])